version: '3'

services:
  webapp:
    container_name: powerpulsesports_app
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - database
    volumes:
      - .:/usr/src/app
  database:
    container_name: powerpulsesports_db
    image: mongo
    ports:
      - "27019:27017"
